[workspace]

members = [
    "agent",
    "client",
    "common",
    "server",
]

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.agent]
opt-level = 'z'
debug = false
debug-assertions = false
